# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dd/ubu20/ppkdmeans3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dd/ubu20/ppkdmeans3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dd/ubu20/ppkdmeans3/CMakeFiles /home/dd/ubu20/ppkdmeans3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dd/ubu20/ppkdmeans3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_sc

# Build rule for target.
test_sc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sc
.PHONY : test_sc

# fast build rule for target.
test_sc/fast:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/build
.PHONY : test_sc/fast

cloud.o: cloud.cpp.o

.PHONY : cloud.o

# target to build an object file
cloud.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/cloud.cpp.o
.PHONY : cloud.cpp.o

cloud.i: cloud.cpp.i

.PHONY : cloud.i

# target to preprocess a source file
cloud.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/cloud.cpp.i
.PHONY : cloud.cpp.i

cloud.s: cloud.cpp.s

.PHONY : cloud.s

# target to generate assembly for a file
cloud.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/cloud.cpp.s
.PHONY : cloud.cpp.s

comparator.o: comparator.cpp.o

.PHONY : comparator.o

# target to build an object file
comparator.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/comparator.cpp.o
.PHONY : comparator.cpp.o

comparator.i: comparator.cpp.i

.PHONY : comparator.i

# target to preprocess a source file
comparator.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/comparator.cpp.i
.PHONY : comparator.cpp.i

comparator.s: comparator.cpp.s

.PHONY : comparator.s

# target to generate assembly for a file
comparator.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/comparator.cpp.s
.PHONY : comparator.cpp.s

func.o: func.cpp.o

.PHONY : func.o

# target to build an object file
func.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/func.cpp.o
.PHONY : func.cpp.o

func.i: func.cpp.i

.PHONY : func.i

# target to preprocess a source file
func.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/func.cpp.i
.PHONY : func.cpp.i

func.s: func.cpp.s

.PHONY : func.s

# target to generate assembly for a file
func.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/func.cpp.s
.PHONY : func.cpp.s

test_sc.o: test_sc.cpp.o

.PHONY : test_sc.o

# target to build an object file
test_sc.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/test_sc.cpp.o
.PHONY : test_sc.cpp.o

test_sc.i: test_sc.cpp.i

.PHONY : test_sc.i

# target to preprocess a source file
test_sc.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/test_sc.cpp.i
.PHONY : test_sc.cpp.i

test_sc.s: test_sc.cpp.s

.PHONY : test_sc.s

# target to generate assembly for a file
test_sc.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/test_sc.cpp.s
.PHONY : test_sc.cpp.s

tools.o: tools.cpp.o

.PHONY : tools.o

# target to build an object file
tools.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/tools.cpp.o
.PHONY : tools.cpp.o

tools.i: tools.cpp.i

.PHONY : tools.i

# target to preprocess a source file
tools.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/tools.cpp.i
.PHONY : tools.cpp.i

tools.s: tools.cpp.s

.PHONY : tools.s

# target to generate assembly for a file
tools.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc.dir/build.make CMakeFiles/test_sc.dir/tools.cpp.s
.PHONY : tools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_sc"
	@echo "... cloud.o"
	@echo "... cloud.i"
	@echo "... cloud.s"
	@echo "... comparator.o"
	@echo "... comparator.i"
	@echo "... comparator.s"
	@echo "... func.o"
	@echo "... func.i"
	@echo "... func.s"
	@echo "... test_sc.o"
	@echo "... test_sc.i"
	@echo "... test_sc.s"
	@echo "... tools.o"
	@echo "... tools.i"
	@echo "... tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

